% Provide feedback on score of last round
function setFeedback(feedback,b,textColor,score,nr_blocks)
    if score(1)>score(2)
        set(feedback, 'string',{sprintf('(block %1g out of %1g)', b, nr_blocks) ''...
            'Congratulations you win this round! Your total score is:' ''...
            sprintf(' you = %3g    comp = %3g', score) ''}, 'Color',textColor);
    elseif score(1)==score(2)
        set(feedback, 'string',{sprintf('(block %1g out of %1g)', b, nr_blocks) ''...
            'It is a draw! Your total score is:' ''...
            sprintf(' you = %3g    comp = %3g', score) ''}, 'Color',textColor);
    else
        set(feedback, 'string',{sprintf('(block %1g out of %1g)', b, nr_blocks) ''...
            'Too bad, you lost this round... Your total score is:' ''...
            sprintf(' you = %3g    comp = %3g', score) ''}, 'Color',textColor);
    end
end