#!/bin/bash
scriptDir=`dirname ${BASH_SOURCE[0]}`
cd $scriptDir
source ../../utilities/findMatlab.sh
if [[ $matexe == *matlab ]]; then  args=-nodesktop; fi
cat <<EOF | $matexe $args
cd $scriptDir
configureIM;
startSigProcBuffer('epochEventType','stimulus.target','freqband',[6 8 28 30],...
                   'clsfr_type','ersp','trlen_ms',trlen_ms,...
                   'calibrateOpts',calibrateOpts,'trainOpts',trainOpts,...
                   'contFeedbackOpts',contFeedbackOpts,...
                   'epochFeedbackOpts',epochFeedbackOpts,...
                   'useGUI',0);
%quit;
EOF
