  %==========================================================================
function str = genTextStr(score,curBalls,cannonKills)
  str = sprintf(['  Shots: %i  |  hits: %i  |  acc.:%.1f%%'...
                   '  |  bonus: %i out of %i  |  Died  %i times           SCORE: %d']...
                ,score.shots,score.hits,100*score.hits/max(1,score.shots)...
                ,score.bonushits, score.totalBonusPoss ,cannonKills,score.score);
end
