--- Makefile	2012-08-26 00:36:40.381908643 +0200
+++ Makefile	2012-03-22 18:29:11.000000000 +0100
@@ -18,6 +18,10 @@
 SUFFIX   =
 RM       = rm -f
 
+ifeq "$(PLATFORM)" "i686-linux-gnu"
+	CFLAGS	 += -DDISABLE_NAGLE
+endif
+
 ifeq "$(PLATFORM)" "mingw32"
 	INCPATH	 = -I../src -I../pthreads-win32/include
 	LIBPATH  = -L../src -L../pthreads-win32/lib
