configureGame;
startSigProcBuffer('epochEventType','stimulus.target','freqband',freqband,...
                   'clsfr_type','ersp','trlen_ms',trlen_ms,...
                   'calibrateOpts',calibrateOpts,'trainOpts',trainOpts,...
                   'contFeedbackOpts',contFeedbackOpts,...
                   'epochFeedbackOpts',epochFeedbackOpts,...
                   'useGUI',0);
